<?php

$dictionary["bh_Scripts_leadership_recommend"]["fields"]["recommend_date"] = array (
    'required' => false,
    'name' => 'recommend_date',
    'vname' => 'LBL_RECOMMEND_DATE',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
);

$dictionary["bh_Scripts_leadership_recommend"]["fields"]["recommend_text"] = array (
    'required' => false,
    'name' => 'recommend_text',
    'vname' => 'LBL_RECOMMEND_TEXT',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
);