<?php
$dictionary['bh_Card_ident']['fields']['date_vidachi'] = array (
      'required' => false,
      'name' => 'date_vidachi',
      'vname' => 'LBL_DATE_VIDACHI',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
);


$dictionary['bh_Card_ident']['fields']['date_activation'] = array (
      'required' => false,
      'name' => 'date_activation',
      'vname' => 'LBL_DATE_ACTIVATION',
      'type' => 'datetimecombo',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
);


$dictionary['bh_Card_ident']['fields']['card_status'] = array (
      'required' => false,
      'name' => 'card_status',
      'vname' => 'LBL_CARD_STATUS',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'options' => 'card_status_list',
      'studio' => 'visible',
      'size' => '20',
      'enable_range_search' => false,
);

$dictionary['bh_Card_ident']['fields']['pin_status'] = array (
      'required' => false,
      'name' => 'pin_status',
      'vname' => 'LBL_CARD_PIN_STATUS',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'options' => 'pin_status_list',
      'studio' => 'visible',
      'size' => '20',
      'enable_range_search' => false,
);



$dictionary['bh_Card_ident']['fields']['block_reason'] = array (
      'required' => false,
      'name' => 'block_reason',
      'vname' => 'LBL_BLOCK_REASON',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'options' => 'block_reason_list',
      'studio' => 'visible',
      'size' => '20',
      'enable_range_search' => false,
);

$dictionary['bh_Card_ident']['fields']['secret_word'] = array (
      'required' => false,
      'name' => 'secret_word',
      'vname' => 'LBL_CODE_WORD',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Кодовое слово',
      'help' => 'Кодовое слово',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'studio' => 'visible',
      'size' => '20',
      'len' => '15',
      'enable_range_search' => false,
);