<?php

$dictionary['bh_Realty']['fields']['realty_type_ownership'] = array (
    'required' => false,
    'name' => 'realty_type_ownership',
    'vname' => 'LBL_TYPE_OWNERSHIP',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'options' => 'realty_type_ownership_list',
    'studio' => 'visible',
    'size' => '20',
    'enable_range_search' => false,
);

$dictionary['bh_Realty']['fields']['realty_method_obtaining'] = array (
    'required' => false,
    'name' => 'realty_method_obtaining',
    'vname' => 'LBL_METHOD_OBTAINING',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'options' => 'realty_method_obtaining_list',
    'studio' => 'visible',
    'size' => '20',
    'enable_range_search' => false,
);

$dictionary['bh_Realty']['fields']['realty_owner_pledge'] = array (
    'required' => false,
    'name' => 'realty_owner_pledge',
    'vname' => 'LBL_OWNER_PLEDGE',
    'type' => 'bool',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
);

$dictionary['bh_Realty']['fields']['realty_property_type'] = array (
    'required' => false,
    'name' => 'realty_property_type',
    'vname' => 'LBL_PROPERTY_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'options' => 'realty_property_type_list',
    'studio' => 'visible',
    'size' => '20',
    'enable_range_search' => false,
);
