<?php
$dictionary['bh_scripts']['fields']['script_status'] = array (
         'required' => false,
          'name' => 'script_status',
          'vname' => 'LBL_SCRIPT_STATUS',
          'type' => 'enum',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'inline_edit' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'options' => 'script_status_list',
          'studio' => 'visible',
          'size' => '20',
          'enable_range_search' => false,
    );