<?php 
 //WARNING: The contents of this file are auto-generated


$dictionary["bh_scr_status_history"]["fields"]["bh_scr_status_history_comment"] = array (
    'required' => false,
    'name' => 'bh_scr_status_history_comment',
    'vname' => 'LBL_RESPONSE_COMMENT',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
);
$dictionary["bh_scr_status_history"]["fields"]["bh_scr_status_history_date"] = array (
    'required' => false,
    'name' => 'bh_scr_status_history_date',
    'vname' => 'LBL_RESPONSE_DATE',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
);

$dictionary['bh_scr_status_history']['fields']['scr_status_history_activation'] = array (
    'required' => false,
    'name' => 'scr_status_history_activation',
    'vname' => 'LBL_DATE_ACTIVATION',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
);
$dictionary['bh_scr_status_history']['fields']['scr_status_history_deactivation'] = array (
    'required' => false,
    'name' => 'scr_status_history_deactivation',
    'vname' => 'LBL_DATE_DEACTIVATION',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
);
$dictionary['bh_scr_status_history']['fields']['scr_status_history_status'] = array (
'required' => false,
          'name' => 'scr_status_history_status',
          'vname' => 'LBL_SCRIPT_STATUS',
          'type' => 'enum',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'inline_edit' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'options' => 'script_status_list',
          'studio' => 'visible',
          'size' => '20',
          'enable_range_search' => false,
    );

$dictionary['bh_scr_status_history']['fields']['scr_status_history_rate_effort'] = array (
    'required' => false,
    'name' => 'scr_status_history_rate_effort',
    'vname' => 'LBL_RATE_EFFORT',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
);
?>