<?php 
 //WARNING: The contents of this file are auto-generated


// created: 2017-09-11 10:02:06
$dictionary["Lead"]["fields"]["bh_card_ident_leads"] = array (
  'name' => 'bh_card_ident_leads',
  'type' => 'link',
  'relationship' => 'bh_card_ident_leads',
  'source' => 'non-db',
  'module' => 'bh_Card_ident',
  'bean_name' => false,
  'vname' => 'LBL_BH_CARD_IDENT_LEADS_FROM_BH_CARD_IDENT_TITLE',
  'id_name' => 'bh_card_ident_leadsbh_card_ident_ida',
);
$dictionary["Lead"]["fields"]["bh_card_ident_leads_name"] = array (
  'name' => 'bh_card_ident_leads_name',
  'type' => 'relate',
  'source' => 'non-db',
  'vname' => 'LBL_BH_CARD_IDENT_LEADS_FROM_BH_CARD_IDENT_TITLE',
  'save' => true,
  'id_name' => 'bh_card_ident_leadsbh_card_ident_ida',
  'link' => 'bh_card_ident_leads',
  'table' => 'bh_card_ident',
  'module' => 'bh_Card_ident',
  'rname' => 'name',
);
$dictionary["Lead"]["fields"]["bh_card_ident_leadsbh_card_ident_ida"] = array (
  'name' => 'bh_card_ident_leadsbh_card_ident_ida',
  'type' => 'link',
  'relationship' => 'bh_card_ident_leads',
  'source' => 'non-db',
  'reportable' => false,
  'side' => 'left',
  'vname' => 'LBL_BH_CARD_IDENT_LEADS_FROM_BH_CARD_IDENT_TITLE',
);



$dictionary['Lead']['fields']['lead_status'] = array (
      'required' => false,
      'name' => 'lead_status',
      'vname' => 'LBL_LEAD_STATUS',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_status_list',
      'studio' => 'visible',
      'dependency' => false,
    );

$dictionary['Lead']['fields']['lead_sex'] = array (
      'required' => false,
      'name' => 'lead_sex',
      'vname' => 'LBL_LEAD_SEX',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_sex_list',
      'studio' => 'visible',
      'dependency' => false,
    );

$dictionary['Lead']['fields']['resident'] = array (
      'required' => false,
      'name' => 'resident',
      'vname' => 'LBL_RESIDENT',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    );

$dictionary['Lead']['fields']['inn']=array (
      'required' => true,
      'name' => 'inn',
      'vname' => 'LBL_INN',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'индивидуальный налоговый номер',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
    );

$dictionary['Lead']['fields']['date_birthday'] = array (
      'required' => false,
      'name' => 'date_birthday',
      'vname' => 'LBL_DATE_BIRTHDAY',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    );

$dictionary['Lead']['fields']['soc_status'] = array (
      'required' => false,
      'name' => 'soc_status',
      'vname' => 'LBL_SOC_STATUS',
      'type' => 'multienum',
      'massupdate' => 0,
      'default' => '^^',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'options' => 'lead_socstatus_list',
      'studio' => 'visible',
      'isMultiSelect' => true,
    );


$dictionary['Lead']['fields']['statliveplace'] = array (
      'required' => false,
      'name' => 'statliveplace',
      'vname' => 'LBL_STATUS_LIVEPLACE',
      'type' => 'multienum',
      'massupdate' => 0,
      'default' => '^^',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'options' => 'lead_statliveplace_list',
      'studio' => 'visible',
      'isMultiSelect' => true,
    );

$dictionary['Lead']['fields']['education'] = array (
      'required' => false,
      'name' => 'education',
      'vname' => 'LBL_EDUCATION',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_education_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['photo'] = array (
      'required' => false,
      'name' => 'photo',
      'vname' => 'LBL_PHOTO',
      'type' => 'image',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Выберите фотографию',
      'help' => 'Выберите фотографию',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 255,
      'size' => '20',
      'studio' => 'visible',
      'dbType' => 'varchar',
      'border' => '1',
      'width' => '120',
      'height' => '240',
    );


$dictionary['Lead']['fields']['ukrpasport_nom'] = array (
      'required' => false,
      'name' => 'ukrpasport_nom',
      'vname' => 'LBL_UKRPASPORT_NOM',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Серия Номер паспорта Украины',
      'help' => 'Серия Номер паспорта Украины',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
);


$dictionary['Lead']['fields']['ukrpas_kemvidan'] = array (
      'required' => false,
      'name' => 'ukrpas_kemvidan',
      'vname' => 'LBL_UKRPASP_KEMVIDAN',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Украинский паспорт кем выдан',
      'help' => 'Украинский паспорт кем выдан',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    );

$dictionary['Lead']['fields']['ukrpas_datavidachy'] = array (
      'required' => false,
      'name' => 'ukrpas_datavidachy',
      'vname' => 'LBL_UKRPASP_DATAVIDACHY',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Украинский паспорт дата выдачи',
      'help' => 'Украинский паспорт дата выдачи',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    );


$dictionary['Lead']['fields']['placebirth']=array (
      'required' => false,
      'name' => 'placebirth',
      'vname' => 'LBL_PLACEBIRTH',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'Место рождения',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '30',
      'size' => '20',
    );


$dictionary['Lead']['fields']['zagrpasport_nom'] = array (
      'required' => false,
      'name' => 'zagrpasport_nom',
      'vname' => 'LBL_ZAGPASPORT_NOM',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Серия Номер загран паспорта Украины',
      'help' => 'Серия Номер загран паспорта Украины',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
);

$dictionary['Lead']['fields']['zagrpas_kemvidan'] = array (
      'required' => false,
      'name' => 'zagrpas_kemvidan',
      'vname' => 'LBL_ZAGRPASP_KEMVIDAN',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => ' Заграничный Украинский паспорт кем выдан',
      'help' => 'Заграничный Украинский паспорт кем выдан',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    );

$dictionary['Lead']['fields']['zagrpas_datavidachy'] = array (
      'required' => false,
      'name' => 'zagrpas_datavidachy',
      'vname' => 'LBL_ZAGRPASP_DATAVIDACHY',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Загран паспорт дата выдачи',
      'help' => 'Загран паспорт дата выдачи',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    );

$dictionary['Lead']['fields']['zagrpas_date_end'] = array (
      'required' => false,
      'name' => 'zagrpas_date_end',
      'vname' => 'LBL_ZAGRPASP_DATEND',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Загран паспорт дата окончания',
      'help' => 'Загран паспорт дата окончания',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    );





$dictionary['Lead']['fields']['pasport_nom_nerezident'] = array (
      'required' => false,
      'name' => 'pasport_nom_nerezident',
      'vname' => 'LBL_PASPORTNOM_NER',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Серия Номер паспорта Нерезидента Украины',
      'help' => 'Серия Номер загран паспорта Нерезидента Украины',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
);


$dictionary['Lead']['fields']['nerezpas_date_vidachi'] = array (
      'required' => false,
      'name' => 'nerezpas_date_vidachi',
      'vname' => 'LBL_NEREZPASP_DATEVIDACHI',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Паспорт Нерезидента Украины дата выдачи',
      'help' => 'Паспорт Нерезидента Украины дата выдачи',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    );

$dictionary['Lead']['fields']['nerezpas_date_end'] = array (
      'required' => false,
      'name' => 'nerezpas_date_end',
      'vname' => 'LBL_NEREZPASP_DATEEND',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Паспорт Нерезидента Украины дата окончания',
      'help' => 'Паспорт Нерезидента Украины дата окончания',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
);

$dictionary['Lead']['fields']['vidnazhit_nom'] = array (
      'required' => false,
      'name' => 'vidnazhit_nom',
      'vname' => 'LBL_VIDNAZHIT',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Серия Номер вида на жительство Нерезидента Украины',
      'help' => 'Серия Номер вида на жительство Нерезидента Украины',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
);


$dictionary['Lead']['fields']['vidnazhit_date_vidachi'] = array (
      'required' => false,
      'name' => 'vidnazhit_date_vidachi',
      'vname' => 'LBL_VIDNAZHIT_DATEVIDACHI',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Вид на жительство дата выдачи',
      'help' => 'Вид на жительство дата выдачи',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
);

$dictionary['Lead']['fields']['vidnazhit_date_end'] = array (
      'required' => false,
      'name' => 'vidnazhit_date_end',
      'vname' => 'LBL_VIDNAZHIT_DATEEND',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Вид на жительство дозволенный срок проживания',
      'help' => 'Вид на жительство дозволенный срок проживания',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
);



$dictionary['Lead']['fields']['problem_law'] = array (
      'required' => false,
      'name' => 'problem_law',
      'vname' => 'LBL_PROBLEMLAW',
      'type' => 'multienum',
      'massupdate' => 0,
      'default' => '^^',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'options' => 'lead_problemlaw_list',
      'studio' => 'visible',
      'isMultiSelect' => true,
);

$dictionary['Lead']['fields']['judded_by_article'] = array (
      'required' => false,
      'name' => 'judded_by_article',
      'vname' => 'LBL_JUDDED_BY',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Судимость по статье',
      'help' => 'Судимость по статье',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    );


$dictionary['Lead']['fields']['family_status'] = array (
      'required' => false,
      'name' => 'family_status',
      'vname' => 'LBL_FAMILYSTATUS',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_familystatus_list',
      'studio' => 'visible',
      'dependency' => false,
);


$dictionary['Lead']['fields']['realty'] = array (
      'required' => false,
      'name' => 'realty',
      'vname' => 'LBL_REALTY',
      'type' => 'multienum',
      'massupdate' => 0,
      'default' => '^^',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'options' => 'lead_realty_list',
      'studio' => 'visible',
      'isMultiSelect' => true,
);

$dictionary['Lead']['fields']['realtyby'] = array (
      'required' => false,
      'name' => 'realtyby',
      'vname' => 'LBL_REALTYBY',
      'type' => 'multienum',
      'massupdate' => 0,
      'default' => '^^',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'options' => 'lead_realtyby_list',
      'studio' => 'visible',
      'isMultiSelect' => true,
);


$dictionary['Lead']['fields']['realty_vid'] = array (
      'required' => false,
      'name' => 'realty_vid',
      'vname' => 'LBL_REALTYVID',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_realtyvid_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['srok_vladenya_nedvizh'] = array (
      'required' => false,
      'name' => 'srok_vladenya_nedvizh',
      'vname' => 'LBL_SROK_VLADENIYA',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => ' Срок владения недвижимым имуществом',
      'help' => 'Срок владения недвижимым имуществом',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    );




$dictionary['Lead']['fields']['transport_owner1'] = array (
      'required' => false,
      'name' => 'transport_owner1',
      'vname' => 'LBL_TRANSOWNER1',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_transowner_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['transport_owner2'] = array (
      'required' => false,
      'name' => 'transport_owner2',
      'vname' => 'LBL_TRANSOWNER2',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_transowner_list',
      'studio' => 'visible',
      'dependency' => false,
);


$dictionary['Lead']['fields']['transport_owner3'] = array (
      'required' => false,
      'name' => 'transport_owner3',
      'vname' => 'LBL_TRANSOWNER3',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_transowner_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['transport_owner4'] = array (
      'required' => false,
      'name' => 'transport_owner4',
      'vname' => 'LBL_TRANSOWNER4',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_transowner_list',
      'studio' => 'visible',
      'dependency' => false,
);







$dictionary['Lead']['fields']['how_buytransport1'] = array (
      'required' => false,
      'name' => 'how_buytransport1',
      'vname' => 'LBL_HOWBUYTRANS1',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_buymode_list',
      'studio' => 'visible',
      'dependency' => false,
);


$dictionary['Lead']['fields']['how_buytransport2'] = array (
      'required' => false,
      'name' => 'how_buytransport2',
      'vname' => 'LBL_HOWBUYTRANS2',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_buymode_list',
      'studio' => 'visible',
      'dependency' => false,
);



$dictionary['Lead']['fields']['how_buytransport3'] = array (
      'required' => false,
      'name' => 'how_buytransport3',
      'vname' => 'LBL_HOWBUYTRANS3',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_buymode_list',
      'studio' => 'visible',
      'dependency' => false,
);


$dictionary['Lead']['fields']['how_buytransport4'] = array (
      'required' => false,
      'name' => 'how_buytransport4',
      'vname' => 'LBL_HOWBUYTRANS4',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'lead_buymode_list',
      'studio' => 'visible',
      'dependency' => false,
);





$dictionary['Lead']['fields']['yearissuetrans1'] = array (
      'required' => false,
      'name' => 'yearissuetrans1',
      'vname' => 'LBL_YEARISSUETR1',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Год выпуска транспорта 1',
      'help' => 'Год выпуска транспорта 1',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '4',
      'size' => '20',
      'options' => 'lead_yeartrans_list',
      'studio' => 'visible',
      'dbType' => 'integer',
);




$dictionary['Lead']['fields']['yearissuetrans2'] = array (
      'required' => false,
      'name' => 'yearissuetrans2',
      'vname' => 'LBL_YEARISSUETR2',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Год выпуска транспорта 2',
      'help' => 'Год выпуска транспорта 2',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '4',
      'size' => '20',
      'options' => 'lead_yeartrans_list',
      'studio' => 'visible',
      'dbType' => 'integer',
);




$dictionary['Lead']['fields']['yearissuetrans3'] = array (
      'required' => false,
      'name' => 'yearissuetrans3',
      'vname' => 'LBL_YEARISSUETR3',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Год выпуска транспорта 3',
      'help' => 'Год выпуска транспорта 3',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '4',
      'size' => '20',
      'options' => 'lead_yeartrans_list',
      'studio' => 'visible',
      'dbType' => 'integer',
);




$dictionary['Lead']['fields']['yearissuetrans4'] = array (
      'required' => false,
      'name' => 'yearissuetrans4',
      'vname' => 'LBL_YEARISSUETR4',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Год выпуска транспорта 4',
      'help' => 'Год выпуска транспорта 4',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '4',
      'size' => '20',
      'options' => 'lead_yeartrans_list',
      'studio' => 'visible',
      'dbType' => 'integer',
);







$dictionary['Lead']['fields']['trans1_manufacturer'] = array (
      'required' => false,
      'name' => 'trans1_manufacturer',
      'vname' => 'LBL_TRANS1MANUFACT',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_manufacturer_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['trans2_manufacturer'] = array (
      'required' => false,
      'name' => 'trans2_manufacturer',
      'vname' => 'LBL_TRANS2MANUFACT',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_manufacturer_list',
      'studio' => 'visible',
      'dependency' => false,
);


$dictionary['Lead']['fields']['trans3_manufacturer'] = array (
      'required' => false,
      'name' => 'trans3_manufacturer',
      'vname' => 'LBL_TRANS3MANUFACT',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_manufacturer_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['trans4_manufacturer'] = array (
      'required' => false,
      'name' => 'trans4_manufacturer',
      'vname' => 'LBL_TRANS4MANUFACT',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_manufacturer_list',
      'studio' => 'visible',
      'dependency' => false,
);



$dictionary['Lead']['fields']['model_trans1'] = array (
      'required' => false,
      'name' => 'model_trans1',
      'vname' => 'LBL_MODEL_TRANS1',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Модель транспорта 1',
      'help' => 'Модель транспорта 1',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '50',
      'size' => '20',
    );

$dictionary['Lead']['fields']['model_trans2'] = array (
      'required' => false,
      'name' => 'model_trans2',
      'vname' => 'LBL_MODEL_TRANS2',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Модель транспорта 2',
      'help' => 'Модель транспорта 2',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '50',
      'size' => '20',
    );



$dictionary['Lead']['fields']['model_trans3'] = array (
      'required' => false,
      'name' => 'model_trans3',
      'vname' => 'LBL_MODEL_TRANS3',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Модель транспорта 3',
      'help' => 'Модель транспорта 3',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '50',
      'size' => '20',
    );

$dictionary['Lead']['fields']['model_trans4'] = array (
      'required' => false,
      'name' => 'model_trans4',
      'vname' => 'LBL_MODEL_TRANS4',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Модель транспорта 4',
      'help' => 'Модель транспорта 4',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '50',
      'size' => '20',
    );





$dictionary['Lead']['fields']['volume_trans1'] = array (
      'required' => false,
      'name' => 'volume_trans1',
      'vname' => 'LBL_VOLUME_TRANS1',
      'type' => 'decimal',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Обьем двигателя транспорта 1',
      'help' => 'Обьем двигателя транспорта 1',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
      'precision' => '1',
    );








$dictionary['Lead']['fields']['volume_trans2'] = array (
      'required' => false,
      'name' => 'volume_trans2',
      'vname' => 'LBL_VOLUME_TRANS2',
      'type' => 'decimal',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Обьем двигателя транспорта 2',
      'help' => 'Обьем двигателя транспорта 2',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
      'precision' => '1',
    );


$dictionary['Lead']['fields']['volume_trans3'] = array (
      'required' => false,
      'name' => 'volume_trans3',
      'vname' => 'LBL_VOLUME_TRANS3',
      'type' => 'decimal',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Обьем двигателя транспорта 3',
      'help' => 'Обьем двигателя транспорта 3',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
      'precision' => '1',
    );

$dictionary['Lead']['fields']['volume_trans4'] = array (
      'required' => false,
      'name' => 'volume_trans4',
      'vname' => 'LBL_VOLUME_TRANS4',
      'type' => 'decimal',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Обьем двигателя транспорта 4',
      'help' => 'Обьем двигателя транспорта 4',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
      'precision' => '1',
    );


$dictionary['Lead']['fields']['fuel_type_trans1'] = array (
      'required' => false,
      'name' => 'fuel_type_trans1',
      'vname' => 'LBL_FUELTYPETRANS1',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_fueltype_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['fuel_type_trans2'] = array (
      'required' => false,
      'name' => 'fuel_type_trans2',
      'vname' => 'LBL_FUELTYPETRANS2',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_fueltype_list',
      'studio' => 'visible',
      'dependency' => false,
);


/**/

$dictionary['Lead']['fields']['fuel_type_trans3'] = array (
      'required' => false,
      'name' => 'fuel_type_trans3',
      'vname' => 'LBL_FUELTYPETRANS3',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_fueltype_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['fuel_type_trans4'] = array (
      'required' => false,
      'name' => 'fuel_type_trans4',
      'vname' => 'LBL_FUELTYPETRANS4',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_fueltype_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['type_owner_trans1'] = array (
      'required' => false,
      'name' => 'type_owner_trans1',
      'vname' => 'LBL_TYPEOWNERTRANS1',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_typeownertrans_list',
      'studio' => 'visible',
      'dependency' => false,
);


$dictionary['Lead']['fields']['type_owner_trans2'] = array (
      'required' => false,
      'name' => 'type_owner_trans2',
      'vname' => 'LBL_TYPEOWNERTRANS2',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_typeownertrans_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['type_owner_trans3'] = array (
      'required' => false,
      'name' => 'type_owner_trans3',
      'vname' => 'LBL_TYPEOWNERTRANS3',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_typeownertrans_list',
      'studio' => 'visible',
      'dependency' => false,
);


$dictionary['Lead']['fields']['type_owner_trans4'] = array (
      'required' => false,
      'name' => 'type_owner_trans4',
      'vname' => 'LBL_TYPEOWNERTRANS4',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_typeownertrans_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['zalog_trans1'] = array (
      'required' => false,
      'name' => 'zalog_trans1',
      'vname' => 'LBL_ZALOGTRANS1',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    );

$dictionary['Lead']['fields']['zalog_trans2'] = array (
      'required' => false,
      'name' => 'zalog_trans2',
      'vname' => 'LBL_ZALOGTRANS2',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    );

$dictionary['Lead']['fields']['zalog_trans3'] = array (
      'required' => false,
      'name' => 'zalog_trans3',
      'vname' => 'LBL_ZALOGTRANS3',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    );

$dictionary['Lead']['fields']['zalog_trans4'] = array (
      'required' => false,
      'name' => 'zalog_trans4',
      'vname' => 'LBL_ZALOGTRANS4',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
    );

$dictionary['Lead']['fields']['orgname']=array (
      'required' => false,
      'name' => 'orgname',
      'vname' => 'LBL_ORGNAME',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'Наименование организации предприятия',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
);

$dictionary['Lead']['fields']['org_legal_form'] = array (
      'required' => false,
      'name' => 'org_legal_form',
      'vname' => 'LBL_ORGLEGALFORM',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_orglegalform_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['org_size'] = array (
      'required' => false,
      'name' => 'org_size',
      'vname' => 'LBL_ORGSIZE',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_orgsize_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['org_sphere'] = array (
      'required' => false,
      'name' => 'org_sphere',
      'vname' => 'LBL_ORGSPHERE',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_orgsphere_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['org_position'] = array (
      'required' => false,
      'name' => 'org_position',
      'vname' => 'LBL_ORGPOSITION',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_orgposition_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['org_specialization']=array (
      'required' => false,
      'name' => 'org_specialization',
      'vname' => 'LBL_ORGSPECIALIZATION',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'Специализация (например, наладчик, машинист и т.д.)',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
);


$dictionary['Lead']['fields']['orgwork_date_start'] = array (
      'required' => false,
      'name' => 'orgwork_date_start',
      'vname' => 'LBL_ORGDATESTART',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Дата создания организации/предприятии и/или дата приема на работу (мес, год)',
      'help' => 'Дата создания организации/предприятии и/или дата приема на работу (мес, год)',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    );

$dictionary['Lead']['fields']['org_owner'] = array (
      'required' => false,
      'name' => 'org_owner',
      'vname' => 'LBL_ORGOWNER',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
);

$dictionary['Lead']['fields']['org_work_months']=array (
      'required' => false,
      'name' => 'org_work_months',
      'vname' => 'LBL_ORGWORKMONTH',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'Срок деятельности в данной организации/предприятии (мес.)',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '2',
      'size' => '5',
);

$dictionary['Lead']['fields']['org_work_years'] = array (
      'required' => false,
      'name' => 'org_work_years',
      'vname' => 'LBL_ORGWORKYEARS',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'Срок деятельности в данной организации/предприятии (лет)',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '4',
      'size' => '5',
);


$dictionary['Lead']['fields']['org_workstage_months']=array (
      'required' => false,
      'name' => 'org_workstage_months',
      'vname' => 'LBL_ORGWORKSTAGEMONTH',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'Общий срок предпринимательства/трудового стажа (мес.)',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '2',
      'size' => '5',
);

$dictionary['Lead']['fields']['org_workstage_years']=array (
      'required' => false,
      'name' => 'org_workstage_years',
      'vname' => 'LBL_ORGWORKSTAGEYEARS',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'Общий срок предпринимательства/трудового стажа (лет)',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '',
      'size' => '5',
);


$dictionary['Lead']['fields']['org_earn_method'] = array (
      'required' => false,
      'name' => 'org_earn_method',
      'vname' => 'LBL_EARNMETHOD',
      'type' => 'multienum',
      'massupdate' => 0,
      'default' => '^^',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'options' => 'lead_earnmethod_list',
      'studio' => 'visible',
      'isMultiSelect' => true,
);


$dictionary['Lead']['fields']['org_earn_level'] = array (
      'required' => false,
      'name' => 'org_earn_level',
      'vname' => 'LBL_ORGEARNLEVEL',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_orgearnlevel_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['org_debentures'] = array (
      'required' => false,
      'name' => 'org_debentures',
      'vname' => 'LBL_DEBENTURES',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
);


$dictionary['Lead']['fields']['debet_type'] = array (
      'required' => false,
      'name' => 'debet_type',
      'vname' => 'LBL_DEBETTYPE',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_debettype_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['debet_type_level'] = array (
      'required' => false,
      'name' => 'debet_type_level',
      'vname' => 'LBL_DEBETTYPELEVEL',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_debettypelevel_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['level_volume'] = array (
      'required' => false,
      'name' => 'level_volume',
      'vname' => 'LBL_LEVELVOLUME',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 50,
      'size' => '20',
      'options' => 'lead_levelvolume_list',
      'studio' => 'visible',
      'dependency' => false,
);

$dictionary['Lead']['fields']['room1_number']=array (
      'required' => false,
      'name' => 'room1_number',
      'vname' => 'LBL_ROOM1NUMBER',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'номер помещения в доме (квартиры, комнаты и др.))',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '4',
      'size' => '5',
);

$dictionary['Lead']['fields']['room2_number']=array (
      'required' => false,
      'name' => 'room2_number',
      'vname' => 'LBL_ROOM2NUMBER',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'номер помещения в доме (квартиры, комнаты и др.))',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '4',
      'size' => '5',
);

$dictionary['Lead']['fields']['flat1_dateregister'] = array (
      'required' => false,
      'name' => 'flat1_dateregister',
      'vname' => 'LBL_DATEREGISTER',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Дата регистрации постоянного места проживания',
      'help' => 'Дата регистрации постоянного места проживания',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    );


$dictionary['Lead']['fields']['regist_term_months_flat1']=array (
      'required' => false,
      'name' => 'regist_term_months_flat1',
      'vname' => 'LBL_REGTERMMONTHSFL1',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Срок регистрации по данному адресу(мес.)',
      'help' => 'Срок регистрации по данному адресу(мес.)',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '4',
      'size' => '5',
);


$dictionary['Lead']['fields']['regist_term_years_flat1']=array (
      'required' => false,
      'name' => 'regist_term_years_flat1',
      'vname' => 'LBL_REGTERMНYEARSFL1',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Срок регистрации по данному адресу(лет)',
      'help' => 'Срок регистрации по данному адресу(лет)',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '4',
      'size' => '5',
);


$dictionary['Lead']['fields']['flat2_datelivestart'] = array (
      'required' => false,
      'name' => 'flat2_datelivestart',
      'vname' => 'LBL_DATELIVESTART',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Дата начала проживания',
      'help' => 'Дата начала проживания',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    );



$dictionary['Lead']['fields']['regist_term_months_flat2']=array (
      'required' => false,
      'name' => 'regist_term_months_flat2',
      'vname' => 'LBL_REGTERMMONTHSFL2',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Срок проживания(мес.)',
      'help' => 'Срок проживания(мес.)',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '4',
      'size' => '5',
);


$dictionary['Lead']['fields']['regist_term_years_flat2'] = array (
      'required' => false,
      'name' => 'regist_term_years_flat2',
      'vname' => 'LBL_REGTERMНYEARSFL2',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Срок проживания (лет)',
      'help' => 'Срок проживания (лет)',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '4',
      'size' => '5',
);




$dictionary['Lead']['fields']['work_address_street'] = array (
      'required' => false,
      'name' => 'work_address_street',
      'vname' => 'LBL_WORK_ADDRESS_STREET',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Адрес места работы улица',
      'help' => 'Адрес места работы улица',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '150',
      'size' => '20',
    );


$dictionary['Lead']['fields']['work_address_city'] = array (
      'required' => false,
      'name' => 'work_address_city',
      'vname' => 'LBL_WORK_ADDRESS_CITY',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Город',
      'help' => 'Город',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '150',
      'size' => '20',
);


$dictionary['Lead']['fields']['work_address_state'] = array (
      'required' => false,
      'name' => 'work_address_state',
      'vname' => 'LBL_WORK_ADDRESS_STATE',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Область',
      'help' => 'Область',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '150',
      'size' => '20',
);



$dictionary['Lead']['fields']['work_address_index'] = array (
      'required' => false,
      'name' => 'work_address_index',
      'vname' => 'LBL_WORK_ADDRESS_INDEX',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Индекс',
      'help' => 'Индекс',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '150',
      'size' => '20',
);


$dictionary['Lead']['fields']['work_address_country'] = array (
      'required' => false,
      'name' => 'work_address_country',
      'vname' => 'LBL_WORK_ADDRESS_COUNTRY',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Страна',
      'help' => 'Страна',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '150',
      'size' => '20',
);


$dictionary['Lead']['fields']['work_room_number']=array (
      'required' => false,
      'name' => 'work_room_number',
      'vname' => 'LBL_WORKROOMNUM',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => 'номер помещения в доме (квартиры, комнаты и др.))',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '4',
      'size' => '5',
);


$dictionary['Lead']['fields']['skype_account'] = array (
      'required' => false,
      'name' => 'skype_account',
      'vname' => 'LBL_SKYPE',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Скайп',
      'help' => 'Скайп',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '40',
      'size' => '20',
);


$dictionary['Lead']['fields']['viber'] = array (
      'required' => false,
      'name' => 'viber',
      'vname' => 'LBL_VIBER',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Вайбер',
      'help' => 'Вайбер',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '40',
      'size' => '20',
);


$dictionary['Lead']['fields']['facebook'] = array (
      'required' => false,
      'name' => 'facebook',
      'vname' => 'LBL_FACEBOOK',
      'type' => 'url',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'ссылка на социальную сеть Facebook',
      'help' => 'ссылка на социальную сеть Facebook',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'dbType' => 'varchar',
      'gen' => '0',
      'link_target' => '_blank',
);

$dictionary['Lead']['fields']['vk'] = array (
      'required' => false,
      'name' => 'vk',
      'vname' => 'LBL_VK',
      'type' => 'url',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'ссылка на социальную сеть вКонтакте',
      'help' => 'ссылка на социальную сеть вКонтакте',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'dbType' => 'varchar',
      'gen' => '0',
      'link_target' => '_blank',
);




$dictionary['Lead']['fields']['twitter'] = array (
      'required' => false,
      'name' => 'twitter',
      'vname' => 'LBL_TWITTER',
      'type' => 'url',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'ссылка на социальную сеть Twitter',
      'help' => 'ссылка на социальную сеть Twitter',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'dbType' => 'varchar',
      'gen' => '0',
      'link_target' => '_blank',
);




$dictionary['Lead']['fields']['odnokl'] = array (
      'required' => false,
      'name' => 'odnokl',
      'vname' => 'LBL_ODNOKL',
      'type' => 'url',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'ссылка на социальную сеть Одноклассники',
      'help' => 'ссылка на социальную сеть Одноклассники',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'dbType' => 'varchar',
      'gen' => '0',
      'link_target' => '_blank',
);




$dictionary['Lead']['fields']['googleplus'] = array (
      'required' => false,
      'name' => 'googleplus',
      'vname' => 'LBL_GOOGLEPLUS',
      'type' => 'url',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'ссылка на социальную сеть Google +',
      'help' => 'ссылка на социальную сеть Google +',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'dbType' => 'varchar',
      'gen' => '0',
      'link_target' => '_blank',
);


$dictionary['Lead']['fields']['instagram'] = array (
      'required' => false,
      'name' => 'instagram',
      'vname' => 'LBL_INSTAGRAM',
      'type' => 'url',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'ссылка на социальную сеть Instagram',
      'help' => 'ссылка на социальную сеть Instagram',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'dbType' => 'varchar',
      'gen' => '0',
      'link_target' => '_blank',
);

$dictionary['Lead']['fields']['phone_addr_registr'] = array (
      'required' => false,
      'name' => 'phone_addr_registr',
      'vname' => 'LBL_PHONE_ADDR_REGISTR',
      'type' => 'phone',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Номер телефона по адресу регистрации',
      'help' => 'Номер телефона по адресу регистрации',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'dbType' => 'varchar',
);

$dictionary['Lead']['fields']['phone_addr_fact'] = array (
      'required' => false,
      'name' => 'phone_addr_fact',
      'vname' => 'LBL_PHONE_ADDRFACT',
      'type' => 'phone',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Номер телефона по фактическому адресу проживания',
      'help' => 'Номер телефона по фактическому адресу проживания',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'dbType' => 'varchar',
);


$dictionary['Lead']['fields']['phone_contact_face'] = array (
      'required' => false,
      'name' => 'phone_contact_face',
      'vname' => 'LBL_PHONE_CONTACTFACE',
      'type' => 'phone',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Номер телефона лица для контакта',
      'help' => 'Номер телефона лица для контакта',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '100',
      'size' => '20',
      'dbType' => 'varchar',
);


$dictionary['Lead']['fields']['account_num'] = array (
      'required' => false,
      'name' => 'account_num',
      'vname' => 'LBL_ACCOUNTNUM',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Скайп',
      'help' => 'Скайп',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '40',
      'size' => '20',
);


$dictionary['Lead']['fields']['bank_name'] = array (
      'required' => false,
      'name' => 'bank_name',
      'vname' => 'LBL_BANKNAME',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '5',
      'cols' => '20',
    );

$dictionary['Lead']['fields']['bank_mfo'] = array (
      'required' => false,
      'name' => 'bank_mfo',
      'vname' => 'LBL_BANKMFO',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '40',
      'size' => '20',
);

$dictionary['Lead']['fields']['bank_emitent_name'] = array (
      'required' => false,
      'name' => 'bank_emitent_name',
      'vname' => 'LBL_BANKEMITENTNAME',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '5',
      'cols' => '20',
);

$dictionary['Lead']['fields']['bank_emitent_mfo'] = array (
      'required' => false,
      'name' => 'bank_emitent_mfo',
      'vname' => 'LBL_BANKEMITENTMFO',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '40',
      'size' => '20',
);

$dictionary['Lead']['fields']['card_num'] = array (
      'required' => false,
      'name' => 'card_num',
      'vname' => 'LBL_CARDNUM',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '40',
      'size' => '20',
);


$dictionary['Lead']['fields']['overdraft'] = array (
      'required' => false,
      'name' => 'overdraft',
      'vname' => 'LBL_OVERDRAFT',
      'type' => 'decimal',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Овердрафт',
      'help' => 'Овердрафт',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => false,
      'reportable' => true,
      'readonly' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '3',
    );

$dictionary['Lead']['fields']['credit_rating'] = array (
      'required' => false,
      'name' => 'credit_rating',
      'vname' => 'LBL_CREDRATING',
      'type' => 'decimal',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Рейтинг кредитоспособности',
      'help' => 'Рейтинг кредитоспособности',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => false,
      'reportable' => true,
      'readonly' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '3',
);


$dictionary['Lead']['fields']['age'] = array (
      'required' => false,
      'name' => 'age',
      'vname' => 'LBL_AGE',
      'type' => 'int',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Возраст',
      'help' => 'Возраст',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '3',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
    );


$dictionary['Lead']['fields']['first_name2'] = array (
      'required' => false,
      'name' => 'first_name2',
      'vname' => 'LBL_FIRSTNAME2',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'История смены имени',
      'help' => 'История смены имени',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '40',
      'size' => '20',
);

$dictionary['Lead']['fields']['last_name2'] = array (
      'required' => false,
      'name' => 'last_name2',
      'vname' => 'LBL_LASTNAME2',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'История смены фамилии',
      'help' => 'История смены фамилии',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'enabled',
      'len' => '40',
      'size' => '20',
);


$dictionary['Lead']['fields']['patronymic'] = array (
      'required' => false,
      'name' => 'patronymic',
      'vname' => 'LBL_PATRONIMYC',
      'type' => 'varchar',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Отчество',
      'help' => 'Отчество',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'enabled',
      'len' => '40',
      'size' => '20',
);


$dictionary['Lead']['fields']['message_to_assigned'] = array (
      'required' => false,
      'name' => 'message_to_assigned',
      'vname' => 'LBL_MESTOASIGNED',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Сообщение для назначаемого пользователя',
      'help' => 'Сообщение для назначаемого пользователя',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'enabled',
      'len' => '0',
      'size' => '40',
      'rows'=>'10',
      'cols'=>'20',
);


$dictionary['Lead']['fields']['child_count'] = array (
      'required' => false,
      'name' => 'child_count',
      'vname' => 'LBL_CHILDCOUNT',
      'type' => 'int',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Количество детей',
      'help' => 'Количество детей',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '2',
      'size' => '5',
      'enable_range_search' => false,
      'disable_num_format' => '1',
      'min' => false,
      'max' => false,
    
);

// created: 2017-09-15 14:36:18
$dictionary["Lead"]["fields"]["leads_bh_packet_activation_1"] = array (
  'name' => 'leads_bh_packet_activation_1',
  'type' => 'link',
  'relationship' => 'leads_bh_packet_activation_1',
  'source' => 'non-db',
  'module' => 'bh_packet_activation',
  'bean_name' => 'bh_packet_activation',
  'side' => 'right',
  'vname' => 'LBL_LEADS_BH_PACKET_ACTIVATION_1_FROM_BH_PACKET_ACTIVATION_TITLE',
);


// created: 2017-09-14 09:55:28
$dictionary["Lead"]["fields"]["leads_cases_1"] = array (
  'name' => 'leads_cases_1',
  'type' => 'link',
  'relationship' => 'leads_cases_1',
  'source' => 'non-db',
  'module' => 'Cases',
  'bean_name' => 'Case',
  'side' => 'right',
  'vname' => 'LBL_LEADS_CASES_1_FROM_CASES_TITLE',
);


// created: 2017-09-14 11:00:22
$dictionary["Lead"]["fields"]["leads_documents_1"] = array (
  'name' => 'leads_documents_1',
  'type' => 'link',
  'relationship' => 'leads_documents_1',
  'source' => 'non-db',
  'module' => 'Documents',
  'bean_name' => 'Document',
  'side' => 'right',
  'vname' => 'LBL_LEADS_DOCUMENTS_1_FROM_DOCUMENTS_TITLE',
);


 // created: 2017-09-03 11:24:49
$dictionary['Lead']['fields']['jjwg_maps_address_c']['inline_edit']=1;

 

 // created: 2017-09-03 11:24:49
$dictionary['Lead']['fields']['jjwg_maps_geocode_status_c']['inline_edit']=1;

 

 // created: 2017-09-03 11:24:49
$dictionary['Lead']['fields']['jjwg_maps_lat_c']['inline_edit']=1;

 

 // created: 2017-09-03 11:24:49
$dictionary['Lead']['fields']['jjwg_maps_lng_c']['inline_edit']=1;

 

 // created: 2017-08-21 10:47:23
$dictionary['Lead']['fields']['lead_status']['options']='leed_status_list';

 

 // created: 2017-08-29 10:22:49

 
?>