<?php



$dictionary['bh_passports']['fields']['passport_num'] = array (
    'required' => false,
    'name' => 'passport_num',
    'vname' => 'LBL_PASSPORT_NUM',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Серия Номер паспорта',
    'help' => 'Серия Номер паспорта',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '10',
    'size' => '20',
);


$dictionary['bh_passports']['fields']['issued_by'] = array (
    'required' => false,
    'name' => 'issued_by',
    'vname' => 'LBL_ISSUED_BY',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'кем выдан',
    'help' => 'кем выдан',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
);

$dictionary['bh_passports']['fields']['date_issue'] = array (
    'required' => false,
    'name' => 'date_issue',
    'vname' => 'LBL_DATE_ISSUE',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'дата выдачи',
    'help' => 'дата выдачи',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
);

$dictionary['bh_passports']['fields']['birthday'] = array (
    'required' => false,
    'name' => 'birthday',
    'vname' => 'LBL_DATE_BIRTHDAY',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Дата рождения',
    'help' => 'Дата рождения',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
);

$dictionary['bh_passports']['fields']['placebirth'] = array (
    'required' => false,
    'name' => 'placebirth',
    'vname' => 'LBL_PLACEBIRTH',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => 'Место рождения',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '30',
    'size' => '20',
);

$dictionary['bh_passports']['fields']['date_expiration'] = array (
    'required' => false,
    'name' => 'date_expiration',
    'vname' => 'LBL_DATE_EXPIRATION',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'дата окончания',
    'help' => 'дата окончания',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
);

$dictionary['bh_passports']['fields']['passport_type'] = array (
    'required' => false,
    'name' => 'passport_type',
    'vname' => 'LBL_PASSPORT_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => '',
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'passport_type_list',
    'studio' => 'visible',
    'dependency' => false,
);


