<?php

$dictionary['Case']['fields']['case_view'] = array (
       'required' => false,
       'name' => 'case_view',
       'vname' => 'LBL_CASE_VIEW',
       'type' => 'enum',
       'massupdate' => 0,
       'no_default' => false,
       'comments' => '',
       'help' => '',
       'importable' => 'true',
       'duplicate_merge' => 'disabled',
       'duplicate_merge_dom_value' => '0',
       'audited' => false,
       'inline_edit' => '',
       'reportable' => true,
       'unified_search' => false,
       'merge_filter' => 'disabled',
       'len' => 50,
       'size' => '20',
       'options' => 'case_view_list',
       'studio' => 'visible',
       'dependency' => false,
);

$dictionary['Case']['fields']['case_type'] = array (
       'required' => false,
       'name' => 'case_type',
       'vname' => 'LBL_CASE_TYPE',
       'type' => 'enum',
       'massupdate' => 0,
       'no_default' => false,
       'comments' => '',
       'help' => '',
       'importable' => 'true',
       'duplicate_merge' => 'disabled',
       'duplicate_merge_dom_value' => '0',
       'audited' => false,
       'inline_edit' => '',
       'reportable' => true,
       'unified_search' => false,
       'merge_filter' => 'disabled',
       'len' => 15,
       'size' => '20',
       'options' => 'case_type_list',
       'studio' => 'visible',
       'dependency' => false,
);


$dictionary['Case']['fields']['case_status'] = array (
       'required' => false,
       'name' => 'case_status',
       'vname' => 'LBL_CASE_STATUS',
       'type' => 'enum',
       'massupdate' => 0,
       'no_default' => false,
       'comments' => '',
       'help' => '',
       'importable' => 'true',
       'duplicate_merge' => 'disabled',
       'duplicate_merge_dom_value' => '0',
       'audited' => false,
       'inline_edit' => '',
       'reportable' => true,
       'unified_search' => false,
       'merge_filter' => 'disabled',
       'len' => 15,
       'size' => '20',
       'options' => 'case_status_list',
       'studio' => 'visible',
       'dependency' => false,
);

$dictionary['Case']['fields']['result_comment'] = array (
    'required' => false,
    'name' => 'result_comment',
    'vname' => 'LBL_RESULT_COMMENT',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
);



$dictionary['Case']['fields']['message_to_assigned'] = array (
      'required' => false,
      'name' => 'message_to_assigned',
      'vname' => 'LBL_MESS_TOASIGNED',
      'type' => 'text',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => 'Сообщение для назначаемого пользователя',
      'help' => 'Сообщение для назначаемого пользователя',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'enabled',
      'len' => '0',
      'size' => '40',
      'rows'=>'10',
      'cols'=>'20',
);
